name: sokerr
description: Simple Result Sum Type
version: 1.1.0
repository: https://github.com/namzug16/sokerr

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0

topics:
  - result
  - pattern-matching
  - types
